# Generated by Django 5.1.6 on 2025-02-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='owned_plants',
            field=models.ManyToManyField(blank=True, related_name='owners', to='garden.plant'),
        ),
    ]
