# Generated by Django 5.1.6 on 2025-02-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'verbose_name': 'Friend Request', 'verbose_name_plural': 'Friend Requests'},
        ),
        migrations.AlterModelOptions(
            name='userstats',
            options={'verbose_name': 'User Stats', 'verbose_name_plural': 'User Stats'},
        ),
    ]
