# Generated by Django 5.1.5 on 2025-02-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersinfo',
            options={'verbose_name': 'User Info', 'verbose_name_plural': 'User Information'},
        ),
    ]
