# Generated by Django 5.1.5 on 2025-02-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_usersinfo_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersinfo',
            old_name='leaves',
            new_name='Leaves',
        ),
        migrations.RenameField(
            model_name='usersinfo',
            old_name='points',
            new_name='Points',
        ),
        migrations.RenameField(
            model_name='usersinfo',
            old_name='UID',
            new_name='Username',
        ),
    ]
