# Generated by Django 5.1.6 on 2025-02-12 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0003_friendrequest"),
        ("user_management", "0004_rename_leaves_usersinfo_leaves_and_more"),
    ]

    operations = []
