# Generated by Django 5.1.6 on 2025-02-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_plant_onmarket'),
        ('user_management', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='owned_plants',
            field=models.ManyToManyField(related_name='owners', to='garden.plant'),
        ),
    ]
