# Generated by Django 4.2.18 on 2025-03-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0006_remove_customuser_friends_friendship_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
