# Generated by Django 5.1.6 on 2025-02-14 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='plant_images/')),
                ('fact', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGarden',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('plant1Id', models.IntegerField(blank=True, null=True)),
                ('plant2Id', models.IntegerField(blank=True, null=True)),
                ('plant3Id', models.IntegerField(blank=True, null=True)),
                ('plant4Id', models.IntegerField(blank=True, null=True)),
                ('plant5Id', models.IntegerField(blank=True, null=True)),
                ('plant6Id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
