# Generated by Django 5.1.6 on 2025-02-14 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergarden',
            name='plant1Id',
        ),
        migrations.RemoveField(
            model_name='usergarden',
            name='plant2Id',
        ),
        migrations.RemoveField(
            model_name='usergarden',
            name='plant3Id',
        ),
        migrations.RemoveField(
            model_name='usergarden',
            name='plant4Id',
        ),
        migrations.RemoveField(
            model_name='usergarden',
            name='plant5Id',
        ),
        migrations.RemoveField(
            model_name='usergarden',
            name='plant6Id',
        ),
        migrations.AddField(
            model_name='usergarden',
            name='plant1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garden_plant1', to='garden.plant'),
        ),
        migrations.AddField(
            model_name='usergarden',
            name='plant2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garden_plant2', to='garden.plant'),
        ),
        migrations.AddField(
            model_name='usergarden',
            name='plant3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garden_plant3', to='garden.plant'),
        ),
        migrations.AddField(
            model_name='usergarden',
            name='plant4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garden_plant4', to='garden.plant'),
        ),
        migrations.AddField(
            model_name='usergarden',
            name='plant5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garden_plant5', to='garden.plant'),
        ),
        migrations.AddField(
            model_name='usergarden',
            name='plant6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garden_plant6', to='garden.plant'),
        ),
    ]
