# Generated by Django 5.1.6 on 2025-02-14 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_remove_usergarden_plant1id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergarden',
            name='plant1',
        ),
        migrations.RemoveField(
            model_name='usergarden',
            name='plant2',
        ),
        migrations.RemoveField(
            model_name='usergarden',
            name='plant3',
        ),
        migrations.RemoveField(
            model_name='usergarden',
            name='plant4',
        ),
        migrations.RemoveField(
            model_name='usergarden',
            name='plant5',
        ),
        migrations.RemoveField(
            model_name='usergarden',
            name='plant6',
        ),
        migrations.AddField(
            model_name='usergarden',
            name='plant1Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot1', to='garden.plant'),
        ),
        migrations.AddField(
            model_name='usergarden',
            name='plant2Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot2', to='garden.plant'),
        ),
        migrations.AddField(
            model_name='usergarden',
            name='plant3Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot3', to='garden.plant'),
        ),
        migrations.AddField(
            model_name='usergarden',
            name='plant4Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot4', to='garden.plant'),
        ),
        migrations.AddField(
            model_name='usergarden',
            name='plant5Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot5', to='garden.plant'),
        ),
        migrations.AddField(
            model_name='usergarden',
            name='plant6Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot6', to='garden.plant'),
        ),
    ]
