# Generated by Django 5.1.6 on 2025-02-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_remove_usergarden_plant1_remove_usergarden_plant2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='onMarket',
            field=models.BooleanField(default=True),
        ),
    ]
