# Generated by Django 4.2.18 on 2025-02-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garden", "0004_plant_onmarket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="price",
            field=models.IntegerField(),
        ),
    ]
