# Generated by Django 5.1.6 on 2025-03-17 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievementId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
                ('rewardValue', models.IntegerField()),
                ('type', models.CharField(choices=[('onPointGain', 'Points Gained'), ('onEventComplete', 'Events Completed'), ('onChallengeComplete', 'Challenges Completed'), ('onVisitSite', 'Visited Website')], default='onPointGain', max_length=20)),
                ('url', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaves', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'User Stats',
                'verbose_name_plural': 'User Stats',
            },
        ),
        migrations.CreateModel(
            name='AchievementParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='incomplete', max_length=10)),
                ('achievementId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagement.achievement')),
            ],
            options={
                'verbose_name': 'Achievement Members',
                'verbose_name_plural': 'Achievement Participants',
            },
        ),
    ]
