# Generated by Django 5.1.6 on 2025-02-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userGarden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant1Id', models.TextField()),
                ('plant2Id', models.TextField()),
                ('plant3Id', models.TextField()),
                ('plant4Id', models.TextField()),
                ('plant5Id', models.TextField()),
                ('plant6Id', models.TextField()),
            ],
        ),
    ]
