# Generated by Django 5.1.6 on 2025-03-16 15:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievementId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
                ('rewardValue', models.IntegerField()),
                ('type', models.CharField(choices=[('onPointGain', 'Points Gained'), ('onEventComplete', 'Events Completed'), ('onChallengeComplete', 'Challenges Completed'), ('onVisitSite', 'Visited Website')], default='onPointGain', max_length=20)),
                ('url', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challengeId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('noOfTasks', models.IntegerField()),
                ('rewardValue', models.IntegerField()),
                ('qrvalue', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('QRImage', models.ImageField(blank=True, default=None, null=True, upload_to='qr_codes/')),
                ('isQR', models.BooleanField(default=False)),
                ('repeatable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='incomplete', max_length=10)),
            ],
            options={
                'verbose_name': 'Challenge Members',
                'verbose_name_plural': 'Challenge Participants',
            },
        ),
        migrations.CreateModel(
            name='AchievementParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='incomplete', max_length=10)),
                ('achievementId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.achievement')),
            ],
            options={
                'verbose_name': 'Achievement Members',
                'verbose_name_plural': 'Achievement Participants',
            },
        ),
    ]
