# Generated by Django 5.1.6 on 2025-02-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='rewardValue',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
