# Generated by Django 5.1.6 on 2025-02-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
