# Generated by Django 5.1.6 on 2025-02-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergarden',
            name='plant1Id',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='usergarden',
            name='plant2Id',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='usergarden',
            name='plant3Id',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='usergarden',
            name='plant4Id',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='usergarden',
            name='plant5Id',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='usergarden',
            name='plant6Id',
            field=models.ImageField(upload_to=''),
        ),
    ]
