# Generated by Django 5.1.6 on 2025-02-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_usergarden_plant1id_alter_usergarden_plant2id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergarden',
            name='plant1Id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usergarden',
            name='plant2Id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usergarden',
            name='plant3Id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usergarden',
            name='plant4Id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usergarden',
            name='plant5Id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usergarden',
            name='plant6Id',
            field=models.TextField(),
        ),
    ]
