# Generated by Django 5.1.6 on 2025-02-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_challenge_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='qrvalue',
            field=models.CharField(default='water', max_length=500),
            preserve_default=False,
        ),
    ]
