# Generated by Django 5.1.6 on 2025-02-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_challengeparticipants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengeparticipants",
            name="status",
            field=models.CharField(
                choices=[("incomplete", "Incomplete"), ("complete", "Complete")],
                default="incomplete",
                max_length=10,
            ),
        ),
    ]
