# Generated by Django 5.1.6 on 2025-02-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_challenge_qrvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='qrvalue',
            field=models.CharField(max_length=50),
        ),
    ]
