# Generated by Django 5.1.6 on 2025-02-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_challenge_qrvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='QRImage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='qrvalue',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
