# Generated by Django 5.1.6 on 2025-02-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_challenge_qrimage_alter_challenge_qrvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='isQR',
            field=models.BooleanField(default=False),
        ),
    ]
