# Generated by Django 5.1.6 on 2025-02-24 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_challenge_qrimage_alter_challenge_qrvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeparticipants',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 24, 12, 56, 48, 856982)),
        ),
    ]
