# Generated by Django 5.1.6 on 2025-02-24 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_challengeparticipants_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeparticipants',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 24, 12, 59, 8, 322989, tzinfo=datetime.timezone.utc)),
        ),
    ]
