# Generated by Django 5.1.6 on 2025-02-24 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_challengeparticipants_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeparticipants',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
