# Generated by Django 5.1.6 on 2025-02-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_challenge_isqr_alter_challengeparticipants_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='repeatable',
            field=models.BooleanField(default=False),
        ),
    ]
