# Generated by Django 5.1.6 on 2025-02-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_challenge_repeatable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='repeatable',
            new_name='repeatble',
        ),
    ]
