# Generated by Django 5.1.6 on 2025-03-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_challengeparticipants_date'),
        ('main', '0010_rename_repeatable_challenge_repeatble'),
    ]

    operations = [
    ]
