# Generated by Django 5.1.6 on 2025-03-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_merge_20250302_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='repeatble',
            new_name='repeatable',
        ),
    ]
