# Generated by Django 5.1.6 on 2025-03-16 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_repeatble_challenge_repeatable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievementId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
                ('rewardValue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AchievementParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='incomplete', max_length=10)),
                ('achievementId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.achievement')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achievement Members',
                'verbose_name_plural': 'Achievement Participants',
                'unique_together': {('username', 'achievementId')},
            },
        ),
    ]
