# Generated by Django 5.1.6 on 2025-03-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_achievement_achievementparticipants'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='type',
            field=models.CharField(choices=[('onPointGain', 'Points Gained')], default='onPointGain', max_length=20),
        ),
    ]
