# Generated by Django 5.1.6 on 2025-03-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_achievement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='url',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='type',
            field=models.CharField(choices=[('onPointGain', 'Points Gained'), ('onEventComplete', 'Events Completed'), ('onChallengeComplete', 'Challenges Completed'), ('onVisitSite', 'Visited Website')], default='onPointGain', max_length=20),
        ),
    ]
