# Generated by Django 5.1.6 on 2025-03-16 23:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challengeId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('noOfTasks', models.IntegerField()),
                ('rewardValue', models.IntegerField()),
                ('qrvalue', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('QRImage', models.ImageField(blank=True, default=None, null=True, upload_to='qr_codes/')),
                ('isQR', models.BooleanField(default=False)),
                ('repeatable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='incomplete', max_length=10)),
                ('challengeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
            ],
            options={
                'verbose_name': 'Challenge Members',
                'verbose_name_plural': 'Challenge Participants',
            },
        ),
    ]
