# Generated by Django 5.1.6 on 2025-03-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='repeatable',
        ),
    ]
