# Generated by Django 5.1.6 on 2025-03-22 06:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='challengeparticipants',
            unique_together={('username', 'challengeId', 'date')},
        ),
    ]
