# Generated by Django 5.1.6 on 2025-02-13 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('noOfTasks', models.IntegerField()),
                ('rewardValue', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('eventMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Events',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.events')),
            ],
            options={
                'verbose_name': 'Event Members',
                'verbose_name_plural': 'Event Participants',
            },
        ),
    ]
