# Generated by Django 5.1.6 on 2025-02-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Event Members',
                'verbose_name_plural': 'Event Participants',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('noOfTasks', models.IntegerField()),
                ('rewardValue', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Events',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
