# Generated by Django 5.1.6 on 2025-03-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='incomplete', max_length=10)),
            ],
            options={
                'verbose_name': 'Event Members',
                'verbose_name_plural': 'Event Participants',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=50)),
                ('noOfTasks', models.IntegerField()),
                ('rewardValue', models.IntegerField()),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('eventQR', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('eventQRImage', models.ImageField(blank=True, default=None, null=True, upload_to='qr_codes/')),
                ('isQR', models.BooleanField(default=False)),
                ('eventImage', models.ImageField(blank=True, default=None, null=True, upload_to='event_images/')),
            ],
            options={
                'verbose_name': 'Events',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
