# Generated by Django 5.1.6 on 2025-02-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="eventQR",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
