# Generated by Django 5.1.6 on 2025-02-12 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventmembers",
            options={
                "verbose_name": "Event Members",
                "verbose_name_plural": "Event Participants",
            },
        ),
        migrations.AlterModelOptions(
            name="events",
            options={"verbose_name": "Events", "verbose_name_plural": "Events"},
        ),
        migrations.AlterUniqueTogether(
            name="eventmembers",
            unique_together=set(),
        ),
    ]
