# Generated by Django 5.1.5 on 2025-02-12 18:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_alter_eventmembers_options_alter_events_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventMembers',
            new_name='EventParticipants',
        ),
    ]
