# Generated by Django 5.1.6 on 2025-02-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_management", "0002_events_eventqr"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="is_qr_event",
            field=models.BooleanField(default=False),
        ),
    ]
