# Generated by Django 5.1.6 on 2025-02-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_management", "0003_rename_eventmembers_eventparticipants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventparticipants",
            name="status",
            field=models.CharField(
                choices=[("incomplete", "Incomplete"), ("complete", "Complete")],
                default="incomplete",
                max_length=10,
            ),
        ),
    ]
