# Generated by Django 5.1.6 on 2025-02-18 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event_management", "0003_events_is_qr_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="events",
            old_name="is_qr_event",
            new_name="isQR",
        ),
    ]
