# Generated by Django 5.1.6 on 2025-02-13 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_management", "0004_alter_eventparticipants_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="rewardValue",
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(1000)]
            ),
        ),
    ]
