# Generated by Django 5.1.6 on 2025-02-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_management", "0004_rename_is_qr_event_events_isqr"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="eventQRImage",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="qr_codes/"
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="eventQR",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
