# Generated by Django 5.1.6 on 2025-03-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_management", "0005_events_eventqrimage_alter_events_eventqr"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="eventImage",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="event_images/"
            ),
        ),
    ]
