# Generated by Django 5.1.6 on 2025-02-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_management", "0005_alter_events_rewardvalue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="desc",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="events",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
