# Generated by Django 5.1.6 on 2025-03-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_management", "0006_events_eventimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="eventImage",
            field=models.ImageField(
                blank=True,
                default="default_event_images/cheese.jpg",
                null=True,
                upload_to="event_images/",
            ),
        ),
    ]
