# Generated by Django 5.1.6 on 2025-02-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_management", "0006_alter_events_desc_alter_events_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="rewardValue",
            field=models.IntegerField(),
        ),
    ]
